USE zju_graduate_art_troupe;
SET @college_id = (SELECT id FROM colleges WHERE name='计算机科学与技术学院' LIMIT 1);
SET @admin_id = (SELECT id FROM users WHERE student_no='TEST_ADMIN_0001');
SET @member_id = (SELECT id FROM users WHERE student_no='TEST_MEMBER_0001');
DELETE FROM attendance_records WHERE user_id=@member_id OR user_id=@admin_id OR project_id IN (SELECT id FROM attendance_projects WHERE title='考勤测试项目1');
DELETE FROM attendance_participants WHERE user_id=@member_id OR user_id=@admin_id OR project_id IN (SELECT id FROM attendance_projects WHERE title='考勤测试项目1');
DELETE FROM attendance_applications WHERE user_id=@member_id OR user_id=@admin_id OR project_id IN (SELECT id FROM attendance_projects WHERE title='考勤测试项目1');
DELETE FROM attendance_projects WHERE title='考勤测试项目1';
DELETE FROM performance_participants WHERE user_id=@member_id OR user_id=@admin_id OR project_id IN (SELECT id FROM performance_projects WHERE name='演出测试项目1');
DELETE FROM performance_applications WHERE user_id=@member_id OR user_id=@admin_id OR project_id IN (SELECT id FROM performance_projects WHERE name='演出测试项目1');
DELETE FROM images WHERE filename='test_performance_image.bin';
DELETE FROM performance_projects WHERE name='演出测试项目1';
DELETE FROM users WHERE student_no IN ('TEST_ADMIN_0001','TEST_MEMBER_0001');
INSERT INTO users (role,name,gender,birthday,student_no,college_id,phone,join_year,status) VALUES ('admin','管理员A','male','1990-01-01','TEST_ADMIN_0001',@college_id,'13800000001',2015,'active');
INSERT INTO users (role,name,gender,birthday,student_no,college_id,phone,join_year,status) VALUES ('member','张三','male','2000-05-12','TEST_MEMBER_0001',@college_id,'13900000001',2018,'active');
SELECT u.id,u.name,u.gender,u.student_no,c.name AS college,u.phone,u.join_year FROM users u JOIN colleges c ON c.id=u.college_id WHERE u.student_no IN ('TEST_ADMIN_0001','TEST_MEMBER_0001');
UPDATE users SET phone='13900000999' WHERE student_no='TEST_MEMBER_0001';
SELECT id,name,phone FROM users WHERE student_no='TEST_MEMBER_0001';
SET @admin_id = (SELECT id FROM users WHERE student_no='TEST_ADMIN_0001');
SET @member_id = (SELECT id FROM users WHERE student_no='TEST_MEMBER_0001');
INSERT INTO attendance_projects (title,location,start_time,end_time,status,created_by) VALUES ('考勤测试项目1','小剧场','2025-01-01 19:00:00','2025-01-01 21:00:00','open',@admin_id);
SET @att_proj_id = (SELECT id FROM attendance_projects WHERE title='考勤测试项目1' LIMIT 1);
INSERT INTO attendance_applications (project_id,user_id,status) VALUES (@att_proj_id,@member_id,'pending');
SELECT id,project_id,user_id,status FROM attendance_applications WHERE project_id=@att_proj_id AND user_id=@member_id;
INSERT INTO attendance_participants (project_id,user_id,source,assigned_by) VALUES (@att_proj_id,@member_id,'application',@admin_id);
SELECT id,project_id,user_id,source FROM attendance_participants WHERE project_id=@att_proj_id;
INSERT INTO attendance_records (project_id,user_id,status,reason,checkin_time,recorded_by) VALUES (@att_proj_id,@member_id,'normal',NULL,'2025-01-01 18:55:00',@admin_id);
SELECT project_id,user_id,status,checkin_time FROM attendance_records WHERE project_id=@att_proj_id;
DELETE FROM attendance_records WHERE project_id=@att_proj_id AND user_id=@member_id;
SELECT COUNT(*) AS cnt FROM attendance_records WHERE project_id=@att_proj_id;
DELETE FROM attendance_applications WHERE project_id=@att_proj_id AND user_id=@member_id;
SELECT COUNT(*) AS cnt FROM attendance_applications WHERE project_id=@att_proj_id;
DELETE FROM attendance_participants WHERE project_id=@att_proj_id AND user_id=@member_id;
SELECT COUNT(*) AS cnt FROM attendance_participants WHERE project_id=@att_proj_id;
DELETE FROM attendance_projects WHERE id=@att_proj_id;
SELECT COUNT(*) AS cnt FROM attendance_projects WHERE id=@att_proj_id;
INSERT INTO performance_projects (name,location,performance_time,rehearsal_time,signup_start,signup_end,status,created_by) VALUES ('演出测试项目1','大礼堂','2025-02-01 19:30:00','2025-01-31 19:30:00','2025-01-01 00:00:00','2025-01-15 23:59:59','open',@admin_id);
SET @perf_proj_id = (SELECT id FROM performance_projects WHERE name='演出测试项目1' LIMIT 1);
INSERT INTO performance_applications (project_id,user_id,status) VALUES (@perf_proj_id,@member_id,'pending');
SELECT id,project_id,user_id,status FROM performance_applications WHERE project_id=@perf_proj_id AND user_id=@member_id;
INSERT INTO performance_participants (project_id,user_id,source,selected_by) VALUES (@perf_proj_id,@member_id,'application',@admin_id);
SELECT id,project_id,user_id,source FROM performance_participants WHERE project_id=@perf_proj_id;
INSERT INTO images (kind,performance_id,uploader_id,filename,mime_type,size_bytes,data) VALUES ('performance',@perf_proj_id,@member_id,'test_performance_image.bin','application/octet-stream',4,X'DEADBEEF');
SELECT id,kind,performance_id,uploader_id,filename,size_bytes FROM images WHERE performance_id=@perf_proj_id;
DELETE FROM images WHERE performance_id=@perf_proj_id;
DELETE FROM performance_participants WHERE project_id=@perf_proj_id AND user_id=@member_id;
DELETE FROM performance_applications WHERE project_id=@perf_proj_id AND user_id=@member_id;
DELETE FROM performance_projects WHERE id=@perf_proj_id;
SELECT COUNT(*) AS cnt FROM performance_projects WHERE id=@perf_proj_id;
DELETE FROM users WHERE student_no IN ('TEST_ADMIN_0001','TEST_MEMBER_0001');
SELECT COUNT(*) AS cnt FROM users WHERE student_no IN ('TEST_ADMIN_0001','TEST_MEMBER_0001');
