 USE zju_graduate_art_troupe;
SET @college_id1 = (SELECT id FROM colleges WHERE name='计算机科学与技术学院' LIMIT 1);
SET @college_id2 = (SELECT id FROM colleges WHERE name='软件学院' LIMIT 1);
DELETE FROM images WHERE performance_id IN (SELECT id FROM performance_projects WHERE name='场景-演出项目A');
DELETE FROM performance_participants WHERE project_id IN (SELECT id FROM performance_projects WHERE name='场景-演出项目A');
DELETE FROM performance_applications WHERE project_id IN (SELECT id FROM performance_projects WHERE name='场景-演出项目A');
DELETE FROM performance_projects WHERE name='场景-演出项目A';
DELETE FROM attendance_records WHERE project_id IN (SELECT id FROM attendance_projects WHERE title='场景-考勤项目A');
DELETE FROM attendance_participants WHERE project_id IN (SELECT id FROM attendance_projects WHERE title='场景-考勤项目A');
DELETE FROM attendance_applications WHERE project_id IN (SELECT id FROM attendance_projects WHERE title='场景-考勤项目A');
DELETE FROM attendance_projects WHERE title='场景-考勤项目A';
DELETE FROM users WHERE student_no IN ('SCENARIO_ADMIN_0001','SCENARIO_MEMBER_0001','SCENARIO_MEMBER_0002');
INSERT INTO users (role,name,gender,birthday,student_no,college_id,phone,join_year,status) VALUES ('admin','管理员X','male','1988-03-10','SCENARIO_ADMIN_0001',@college_id1,'13800000111',2014,'active');
INSERT INTO users (role,name,gender,birthday,student_no,college_id,phone,join_year,status) VALUES ('member','张三','male','2001-06-20','SCENARIO_MEMBER_0001',@college_id1,'13900000111',2018,'active');
INSERT INTO users (role,name,gender,birthday,student_no,college_id,phone,join_year,status) VALUES ('member','李四','female','2002-09-15','SCENARIO_MEMBER_0002',@college_id2,'13900000222',2020,'active');
SELECT id,name,gender,student_no,phone,join_year FROM users WHERE student_no IN ('SCENARIO_ADMIN_0001','SCENARIO_MEMBER_0001','SCENARIO_MEMBER_0002');
SET @admin_id = (SELECT id FROM users WHERE student_no='SCENARIO_ADMIN_0001');
SET @member_id1 = (SELECT id FROM users WHERE student_no='SCENARIO_MEMBER_0001');
SET @member_id2 = (SELECT id FROM users WHERE student_no='SCENARIO_MEMBER_0002');
SET @gid_root = (SELECT id FROM troupe_groups WHERE name='总团' LIMIT 1);
SET @gid_dance = (SELECT id FROM troupe_groups WHERE name='舞蹈分团' LIMIT 1);
SET @gid_vocal = (SELECT id FROM troupe_groups WHERE name='声乐分团' LIMIT 1);
INSERT INTO user_groups (group_id,user_id,role) VALUES (@gid_root,@admin_id,'leader');
INSERT INTO user_groups (group_id,user_id,role) VALUES (@gid_dance,@member_id1,'member');
INSERT INTO user_groups (group_id,user_id,role) VALUES (@gid_vocal,@member_id2,'deputy');
SELECT g.name AS group_name,u.name AS user_name,ug.role FROM user_groups ug JOIN users u ON u.id=ug.user_id JOIN troupe_groups g ON g.id=ug.group_id ORDER BY g.name,u.id;
UPDATE users SET phone='13900000988', college_id=@college_id2 WHERE id=@member_id1;
SELECT id,name,phone FROM users WHERE id=@member_id1;
UPDATE users SET phone='13900000977' WHERE id=@member_id1;
SELECT id,name,phone FROM users WHERE id=@member_id1;
INSERT INTO attendance_projects (title,location,start_time,end_time,status,created_by) VALUES ('场景-考勤项目A','活动室A','2025-03-01 19:00:00','2025-03-01 21:00:00','open',@admin_id);
SET @att_proj_id = (SELECT id FROM attendance_projects WHERE title='场景-考勤项目A');
INSERT INTO attendance_applications (project_id,user_id,status) VALUES (@att_proj_id,@member_id1,'pending');
SELECT id,project_id,user_id,status FROM attendance_applications WHERE project_id=@att_proj_id;
INSERT INTO attendance_participants (project_id,user_id,source,assigned_by) VALUES (@att_proj_id,@member_id1,'application',@admin_id);
INSERT INTO attendance_participants (project_id,user_id,source,assigned_by) VALUES (@att_proj_id,@member_id2,'assigned',@admin_id);
SELECT project_id,user_id,source FROM attendance_participants WHERE project_id=@att_proj_id ORDER BY user_id;
INSERT INTO attendance_records (project_id,user_id,status,reason,checkin_time,recorded_by) VALUES (@att_proj_id,@member_id1,'normal',NULL,'2025-03-01 18:58:00',@admin_id);
UPDATE attendance_records SET status='late', checkin_time='2025-03-01 19:10:00' WHERE project_id=@att_proj_id AND user_id=@member_id1;
INSERT INTO attendance_records (project_id,user_id,status,reason,checkin_time,recorded_by) VALUES (@att_proj_id,@member_id2,'leave','课程冲突',NULL,@admin_id);
SELECT user_id,status,reason,checkin_time FROM attendance_records WHERE project_id=@att_proj_id ORDER BY user_id;
INSERT INTO performance_projects (name,location,performance_time,rehearsal_time,signup_start,signup_end,status,created_by) VALUES ('场景-演出项目A','礼堂A','2025-04-10 19:30:00','2025-04-09 19:30:00','2025-03-20 00:00:00','2025-03-30 23:59:59','open',@admin_id);
SET @perf_proj_id = (SELECT id FROM performance_projects WHERE name='场景-演出项目A');
INSERT INTO performance_applications (project_id,user_id,status) VALUES (@perf_proj_id,@member_id1,'pending');
SELECT id,project_id,user_id,status FROM performance_applications WHERE project_id=@perf_proj_id;
INSERT INTO performance_participants (project_id,user_id,source,selected_by) VALUES (@perf_proj_id,@member_id1,'application',@admin_id);
INSERT INTO performance_participants (project_id,user_id,source,selected_by) VALUES (@perf_proj_id,@member_id2,'assigned',@admin_id);
SELECT project_id,user_id,source FROM performance_participants WHERE project_id=@perf_proj_id ORDER BY user_id;
INSERT INTO images (kind,performance_id,uploader_id,filename,mime_type,size_bytes,data) VALUES ('performance',@perf_proj_id,@member_id1,'scenario_img_member1.bin','application/octet-stream',4,X'CAFEBABE');
INSERT INTO images (kind,performance_id,uploader_id,filename,mime_type,size_bytes,data) VALUES ('performance',@perf_proj_id,@member_id2,'scenario_img_member2.bin','application/octet-stream',4,X'DEADBEEF');
SELECT id,performance_id,uploader_id,filename,size_bytes FROM images WHERE performance_id=@perf_proj_id ORDER BY uploader_id;
INSERT INTO performance_programs (project_id,title,type,duration_seconds,program_order,remarks,contact_phone) VALUES (@perf_proj_id,'节目一','舞蹈',300,1,'开场','13800000111');
INSERT INTO performance_programs (project_id,title,type,duration_seconds,program_order,remarks,contact_phone) VALUES (@perf_proj_id,'节目二','歌曲',240,2,'压轴','13800000111');
SET @prog1 = (SELECT id FROM performance_programs WHERE project_id=@perf_proj_id AND program_order=1);
SET @prog2 = (SELECT id FROM performance_programs WHERE project_id=@perf_proj_id AND program_order=2);
INSERT INTO performance_program_performers (program_id,user_id,role) VALUES (@prog1,@member_id2,'领舞');
INSERT INTO performance_program_performers (program_id,user_id,role) VALUES (@prog1,@member_id1,'伴舞');
INSERT INTO performance_program_performers (program_id,user_id,role) VALUES (@prog2,@member_id1,'主唱');
SELECT program_id,user_id,role FROM performance_program_performers WHERE program_id IN (@prog1,@prog2) ORDER BY program_id,user_id;
DELETE FROM images WHERE performance_id=@perf_proj_id;
DELETE FROM performance_participants WHERE project_id=@perf_proj_id;
DELETE FROM performance_applications WHERE project_id=@perf_proj_id;
DELETE FROM performance_program_performers WHERE program_id IN (SELECT id FROM performance_programs WHERE project_id=@perf_proj_id);
DELETE FROM performance_programs WHERE project_id=@perf_proj_id;
DELETE FROM performance_projects WHERE id=@perf_proj_id;
DELETE FROM attendance_records WHERE project_id=@att_proj_id;
DELETE FROM attendance_participants WHERE project_id=@att_proj_id;
DELETE FROM attendance_applications WHERE project_id=@att_proj_id;
DELETE FROM attendance_projects WHERE id=@att_proj_id;
DELETE FROM user_groups WHERE user_id IN (@member_id1,@member_id2,@admin_id);
DELETE FROM users WHERE id IN (@member_id1,@member_id2,@admin_id);
SELECT COUNT(*) AS cnt_users FROM users WHERE id IN (@member_id1,@member_id2,@admin_id);
SELECT COUNT(*) AS cnt_att_proj FROM attendance_projects WHERE id=@att_proj_id;
SELECT COUNT(*) AS cnt_perf_proj FROM performance_projects WHERE id=@perf_proj_id;
